apiVersion : apps/v1
kind: Deployment
metadata:
  name: test1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1 
    spec:
      containers:
        - name: test1 
          image: ctsdemo.azurecr.io/test1
          ports:
          - containerPort: 80