apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db1
  name: db1
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db1
  
  template:
    metadata:
  
      labels:
        app: db1
    spec:
      containers:
      - image: ctsdemo.azurecr.io:
        name: app
  